name = "alicesaidhi/conch_vm"
version = "0.2.0"
includes = ["src/*", "pesde.toml"]

[target]
environment = "roblox"
lib = "src/lib.luau"
build_files = ["src"]

[indices]
default = "https://github.com/daimond113/pesde-index"

[dependencies]
types = { workspace = "alicesaidhi/conch_types", version = "^" }