# This file lists tools managed by Rokit, a toolchain manager for Roblox projects.
# For more information, see https://github.com/rojo-rbx/rokit

# New tools can be added by running `rokit add <tool>` in a terminal.

[tools]
pesde = "daimond113/pesde@0.5.2+registry.0.1.1"
zap = "red-blox/zap@0.6.16"
rojo = "rojo-rbx/rojo@7.4.4"
