name = "alicesaidhi/conch_glue"
version = "0.1.0"
includes = ["src/", "pesde.toml"]

[target]
environment = "roblox"
lib = "src/lib.luau"
build_files = ["src/"]

[indices]
default = "https://github.com/daimond113/pesde-index"

[dependencies]
ast = { workspace = "alicesaidhi/conch_ast", version = "^", target = "roblox" }
compiler = { workspace = "alicesaidhi/conch_compiler", version = "^", target = "roblox" }
vm = { workspace = "alicesaidhi/conch_vm", version = "^", target = "roblox" }
types = { workspace = "alicesaidhi/conch_types", version = "^", target = "roblox" }
intel = { workspace = "alicesaidhi/conch_analysis", version = "^", target = "roblox" }
