name = "alicesaidhi/conch_standalone"
version = "0.2.0"
includes = ["src/**", "pesde.toml"]
private = true

[target]
environment = "roblox"
lib = "src/lib.luau"
build_files = ["src"]

[indices]
default = "https://github.com/daimond113/pesde-index"

[dependencies]
conch = { workspace = "alicesaidhi/conch", version = "^" }
ui = { workspace = "alicesaidhi/conch_ui", version = "^" }